const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const GET_SIGHTINGS = "GET_SIGHTINGS"
const ADD_SIGHTING = "ADD_SIGHTING"
const EDIT_SIGHTING = "EDIT_SIGHTING"

export {
  SET_CURRENT_USER,
  CLEAR_CURRENT_USER,
  GET_SIGHTINGS,
  ADD_SIGHTING,
  EDIT_SIGHTING
}