const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const GET_SIGHTINGS = "GET_SIGHTINGS"
const ADD_SIGHTING = "ADD_SIGHTING"
const EDIT_SIGHTING = "EDIT_SIGHTING"
const DELETE_SIGHTING = "DELETE_SIGHTING"
const SET_SELECTED_SIGHTING = "SET_SELECTED_SIGHTING"
const UNSET_SIGHTING = "UNSET_SIGHTING"
const COMMENT_FORM_CHANGE = "COMMENT_FORM_CHANGE"
const SET_COMMENT = "SET_COMMENT"
const EDIT_COMMENT = "EDIT_COMMENT"
const DELETE_COMMENT = "DELETE_COMMENT"
const FILTERS_FORM_CHANGE = "FILTERS_FORM_CHANGE"

export {
  SET_CURRENT_USER,
  CLEAR_CURRENT_USER,
  GET_SIGHTINGS,
  ADD_SIGHTING,
  EDIT_SIGHTING,
  DELETE_SIGHTING,
  SET_SELECTED_SIGHTING,
  UNSET_SIGHTING,
  COMMENT_FORM_CHANGE,
  SET_COMMENT,
  EDIT_COMMENT,
  DELETE_COMMENT,
  FILTERS_FORM_CHANGE
}